-Wno-MULTIDRIVEN
-y $JTFRAME/hdl/video
-y $JTFRAME/hdl/ram
-y $JTFRAME/hdl/sound
-y $JTFRAME/hdl/clocking
-y $JTFRAME/hdl/sdram
-y $JTFRAME/hdl
-y $JTFRAME/hdl/cpu
-y $JTFRAME/hdl/cpu/mc6502
-y $MODULES/jt89/hdl

